import {pathToFileURL, fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import {readFile, writeFile} from 'node:fs/promises';
const {chromium} = await import(process.env.PLAYWRIGHT_MODULE_PATH ? pathToFileURL(process.env.PLAYWRIGHT_MODULE_PATH).href : 'playwright');
const browser = await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL || 'msedge'});
try {
  const page = await browser.newPage({viewport:{width:390,height:844},acceptDownloads:true});
  const errors = []; let modelRequests = 0;
  page.on('pageerror', e => errors.push(e.message));
  page.on('request', r => { if (r.url().endsWith('.task')) modelRequests++; });
  await page.goto(process.env.TEST_URL || 'http://127.0.0.1:4180/dist/');
  await page.locator('#camera-file').setInputFiles(fileURLToPath(new URL('./artifacts/reference.webm',import.meta.url)));
  await page.locator('#analyze').click();
  await page.locator('#results').waitFor({state:'visible',timeout:180000});
  const original = await page.locator('.frequency').allTextContents();
  const originalCount = (await page.locator('#sampling').innerText()).match(/^(\d+) images/)[1];
  const pointsBefore = page.waitForEvent('download');
  await page.locator('#export-data').click();
  const originalPoints = await readFile(await (await pointsBefore).path(), 'utf8');
  assert.ok(original.every(x => x.includes('5.0')));
  await page.locator('.spectral-details summary').first().click();
  assert.equal(await page.locator('.spectral-details table').first().isVisible(),true);
  await page.locator('.spectral-details').first().scrollIntoViewIfNeeded();
  await page.screenshot({path:fileURLToPath(new URL('./artifacts/spectral-mobile.png',import.meta.url)),fullPage:true});
  await page.locator('.spectral-details').first().screenshot({path:fileURLToPath(new URL('./artifacts/spectral-panel.png',import.meta.url))});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= window.innerWidth), true);
  const before = modelRequests;
  const start = Date.now();
  await page.locator('#analyze').click();
  await page.locator('#results').waitFor({state:'visible',timeout:30000});
  assert.deepEqual(await page.locator('.frequency').allTextContents(), original);
  assert.match(await page.locator('#sampling').innerText(),/coordonnées réutilisées/);
  assert.equal((await page.locator('#sampling').innerText()).match(/^(\d+) images/)[1], originalCount);
  assert.equal(modelRequests, before, 'Recalculation must not reload the detector');
  const recalculationMs = Date.now()-start;
  const pointsAfter = page.waitForEvent('download');
  await page.locator('#export-data').click();
  assert.equal(await readFile(await (await pointsAfter).path(), 'utf8'), originalPoints);
  await page.getByText('Paramètres d’analyse',{exact:true}).click();
  await page.locator('#low').fill('3'); await page.locator('#high').fill('12');
  await page.locator('#analyze').click();
  await page.locator('#results').waitFor({state:'visible',timeout:30000});
  assert.match(await page.locator('#results').innerText(), /3.0–12.0 Hz/);
  assert.deepEqual(await page.locator('.frequency').allTextContents(), original);
  assert.equal(modelRequests,before);
  const download = page.waitForEvent('download');
  await page.locator('#export-spectrum').click();
  await (await download).saveAs(fileURLToPath(new URL('./artifacts/spectrum.csv',import.meta.url)));
  const report = {frequency:original, preservedFrames:originalCount, exactCoordinatesPreserved:true, changedBand:true, recalculationMs, modelRequests, errors};
  console.log(report);
  await writeFile(new URL('./artifacts/spectral-ui.json',import.meta.url), JSON.stringify(report,null,2));
  assert.deepEqual(errors,[]);
  await page.locator('#clear').click();
  assert.equal(await page.locator('#workspace').isVisible(),false);
} finally { await browser.close(); }
